language: python
python:
  - "3.11" 

# Commande pour exécuter le script
script:
  - python OSDetector.py

# Notifications (optionnelles)
notifications:
  email:
    recipients:
      - VOTRE_ADRESSE_MAIL@example.com
    on_success: always
    on_failure: always
